#include<windows.h>

#define IDC_SLIDER 100

#define IDT_ACCEPT_INPUT 200

#define IDI_TASK_TRAY 300

#define IDM_OPEN_FROM_TASK_TRAY 400
#define IDM_CLOSE_FROM_TASK_TRAY 401

#define IDC_STATIC_CONTROL 500

#define IDC_RADIO_BUTTON 600

#define WM_UPDATE_VOLUME WM_APP + 1
#define WM_TASK_TRAY_CLIKED WM_APP + 2

