#ifndef ID_HEADER_
#define ID_HEADER_

#include<windows.h>

#define IDC_SLIDER 100

#define IDT_ACCEPT_INPUT 200

#define IDI_TASK_TRAY 300

#define IDM_OPEN_FROM_TASK_TRAY 400
#define IDM_CLOSE_FROM_TASK_TRAY 401

#define IDC_STATIC_CONTROL 500

#define IDC_RADIO_BUTTON 600

#define IDI_APPLICATION 700
#define IDI_SHORTCUTKEY_DLG 701
#define IDC_SHORTCUTKEY_DLG_LABEL1 702
#define IDC_SHORTCUTKEY_DLG_LABEL2 703
#define IDC_SHORTCUTKEY_DLG_OK 704
#define IDC_SHORTCUTKEY_DLG_CANCEL 705
#define IDC_SHORTCUTKEY_DLG_EDIT_UP1 706
#define IDC_SHORTCUTKEY_DLG_EDIT_UP2 707
#define IDC_SHORTCUTKEY_DLG_EDIT_UP3 708
#define IDC_SHORTCUTKEY_DLG_EDIT_DOWN1 709
#define IDC_SHORTCUTKEY_DLG_EDIT_DOWN2 710
#define IDC_SHORTCUTKEY_DLG_EDIT_DOWN3 711
#define IDC_SHORTCUTKEY_DLG_PLUS1 712
#define IDC_SHORTCUTKEY_DLG_PLUS2 713
#define IDC_SHORTCUTKEY_DLG_PLUS3 714
#define IDC_SHORTCUTKEY_DLG_PLUS4 715

#define IDC_BUTTON 800

#define WM_UPDATE_VOLUME WM_APP + 1
#define WM_TASK_TRAY_CLIKED WM_APP + 2

#endif
